/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e9ddff",
        "background": "#0f131d",
        "error-container": "#93000a",
        "surface-container-highest": "#313540",
        "surface": "#0f131d",
        "on-primary-fixed": "#23005c",
        "primary-fixed-dim": "#d0bcff",
        "on-secondary": "#00354a",
        "primary": "#d0bcff",
        "on-surface": "#dfe2f1",
        "on-secondary-fixed": "#001e2c",
        "on-primary-fixed-variant": "#5516be",
        "primary-container": "#a078ff",
        "outline": "#958ea0",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface-variant": "#cbc3d7",
        "tertiary-container": "#00a572",
        "surface-container-lowest": "#0a0e18",
        "secondary-container": "#00a6e0",
        "inverse-on-surface": "#2c303b",
        "on-primary": "#3c0091",
        "surface-container-high": "#262a35",
        "on-background": "#dfe2f1",
        "secondary-fixed": "#c4e7ff",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#6ffbbe",
        "outline-variant": "#494454",
        "tertiary": "#4edea3",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary": "#003824",
        "surface-container": "#1c1f2a",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#7bd0ff",
        "on-primary-container": "#340080",
        "surface-dim": "#0f131d",
        "on-error-container": "#ffdad6",
        "surface-tint": "#d0bcff",
        "inverse-surface": "#dfe2f1",
        "inverse-primary": "#6d3bd7",
        "surface-bright": "#353944",
        "on-tertiary-container": "#00311f",
        "on-tertiary-fixed": "#002113",
        "surface-variant": "#313540",
        "on-secondary-container": "#00374d",
        "surface-container-low": "#171b26",
        "secondary": "#7bd0ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-hero-mobile": ["Inter"],
        "label-code": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "display-hero": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["18px", {"lineHeight": "26px", "fontWeight": "600"}],
        "display-hero-mobile": ["36px", {"lineHeight": "44px", "fontWeight": "800"}],
        "label-code": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "headline-lg": ["36px", {"lineHeight": "44px", "fontWeight": "700"}],
        "display-hero": ["56px", {"lineHeight": "64px", "fontWeight": "800"}],
        "body-sm": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "16px", "fontWeight": "700"}],
        "body-md": ["15px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
